explain: |md
  # Layer 3
  This is the third layer, with even more detail. 
  Click the title to go back to the previous layer.
| {
  near: top-center
  link: _
}

frontend: Frontend
bff: Backend for frontend
internal_system: Internal system
